


name: Build CI wheels

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
      - uses: snickerbockers/submodules-init@v4

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==2.1.1 pybind11==2.7.1 ninja meson
      - name: Build C++ with meson
        run : |
          meson builddir --buildtype=release -Dbuild_tests=false && cd builddir && ninja
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./wheelhouse/*.whl